version: '3'

services:
  app:
    image: kopiro/kopiro:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    entrypoint: ['npm', 'run', 'dev']
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./views:/app/views
      - ./routes:/app/routes
      - ./app.js:/app/app.js
      - ./updater.js:/app/updater.js
      - ./server.js:/app/server.js
      - ./db:/app/db
    env_file:
      - .env

  nginx:
    image: kopiro/kopiro:latest-nginx
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./public:/www
      - ./render-data:/www/render
    env_file:
      - .env

  render:
    image: kopiro/kopiro:latest-render
    build:
      context: .
      dockerfile: ./Dockerfile-render
    restart: on-failure
    volumes:
      - ./render-data:/screenshots
