version: '3'

networks:
  proxy:
    external:
      true
  kopiro:

services:
  app:
    image: kopiro/kopiro:latest
    restart: always
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - kopiro

  nginx:
    image: kopiro/kopiro:latest-nginx
    restart: always
    volumes:
      - ./render-data:/www/public/render
    env_file:
      - .env
    networks:
      - proxy
      - kopiro

  render:
    image: kopiro/kopiro:latest-render
    restart: always
    volumes:
      - ./render-data:/screenshots
    networks:
      - kopiro