version: "3"

services:
  app:
    image: kopiro/kopiro:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: "yarn dev"

  nginx:
    image: kopiro/kopiro:latest-nginx
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    restart: on-failure
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./public:/www
