version: '3'

services:
  app:
    image: kopiro/kopiro:latest
    restart: always
    volumes:
      - ./db:/app/db
    env_file:
      - .env

  nginx:
    image: kopiro/kopiro:latest-nginx
    restart: always
    volumes:
      - ./render-data:/www/public/render
    env_file:
      - .env

  render:
    image: kopiro/kopiro:latest-render
    restart: always
    volumes:
      - ./render-data:/screenshots
