version: '3'

services:
  app:
    image: kopiro/kopiro
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REBUILD=1